version: "3.9"

services:

  redis:
    image: redis:7
    container_name: secure-redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: app/Dockerfile
    container_name: secure-backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis
    restart: unless-stopped

  frontend:
    build: ./frontend/secure-token-frontend
    container_name: secure-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
    restart: unless-stopped