version: "3.9"

services:

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6380:6379"
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: app/Dockerfile
    container_name: secure-backend
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
    restart: unless-stopped

  frontend:
    build: ./frontend/secure-token-frontend
    container_name: secure-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
    restart: unless-stopped